.TH "lmserver" "6" "0.1" "AGWA, Greywhind, Archaemic" "Games"
.SH "NAME"
.LP 
lmserver \- The server for Leges Motus, a team\-based, networked, 2D shooter set in zero\-gravity
.SH "SYNTAX"
.LP 
lmserver [\-c \fIconffile\fP] [\-d] [\-l] [\-m \fImapname\fP] [\-P \fIpassword\fP] [\-p \fIportno\fP]
.br 

Only the most useful options are listed here; see below for the remainder.
.SH "DESCRIPTION"
.LP 
Leges Motus is a networked, team\-based, 2D shooter set in zero\-gravity. Using only the force from jumping off of walls and the recoil from their guns, players must travel across the arena to lower their opponent's gate.
.LP 
This is the server program for Leges Motus.  It listens on a UDP port for packets from clients, and relays them to other connected clients.  In addition, the server is responsible for scorekeeping, team assignment, timing the gates, and notifying the clients of the map and rules in play.
.SH "OPTIONS"
.LP 
The following command line options are supported.  Note that some options can also be specified in the server configuration file (see \fBCONFIGURATION\fR below).  Option values specified on the command line \fIalways\fP override option values specified in the configuration file.
.TP 
\fB\-c <\fIconffile\fP>\fR
Load server configuration options (see \fBCONFIGURATION\fR below) from <\fIconffile\fP>.
.TP 
\fB\-d\fR
Daemonize (i.e. run in background) the server program (does not work on Windows).
.TP 
\fB\-l\fR
(Local server) Do not register the server with the meta server.
.TP 
\fB\-m\fR <\fImapname\fP>\fR
Sets the server map to <\fImapname\fP>.  (config option: \fBmap\fR) (default: alpha1)
.TP 
\fB\-P\fR <\fIpassword\fP>\fR
Enables operator mode and sets the operator password to <\fIpassword\fP>.  Warning: using this option will expose the operator password to other users of the system using a command such as \fIps\fR\|(1).  You should use the \fBpassword\fR configuration option instead.
.TP 
\fB\-u\fR <\fIuser\fP>\fR
Drop privileges to <\fIuser\fP> (e.g. nobody).  By default, privileges are not dropped.  Only the super user may use this option.  Not supported on Windows.
.TP 
\fB\-g\fR <\fIgroup\fP>\fR
Drop group privileges to <\fIgroup\fP> (e.g. nogroup).  By default, privileges are not dropped.  Only the super user may use this option.  Not supported on Windows.
.TP 
\fB\-i\fR <\fIinterface\fP>\fR
Listen only on the interface with address <\fIinterface\fP>.  (config option: \fBinterface\fR) (by default, listen on all interfaces)
.TP 
\fB\-p\fR <\fIportno\fP>\fR
Listen on port <\fIportno\fP>.  (config option: \fBportno\fR) (default: 16877)
.TP 
\fB\-?\fR, \fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "COMMANDS"
.LP 
These commands are entered in the client's chat bar (see \fIlegesmotus\fR\|(6)).  Some commands (marked as [op]) require operator status.
.TP 
\fB/server auth <\fIpassword\fP>\fR
Become operator, if <\fIpassword\fP> matches the server operator password.
.TP 
\fB/server teamscore\fR
Display the score of each team.
.TP 
\fB/server teamcount\fR
Display the number of players on each team.
.TP 
\fB/server maps\fR
Display a list of maps available on the server.
.TP 
\fB/server balance\fR
Balance the teams by reassigning players as necessary.  (See also the \fBautobalance\fR configuration option below.)  [op]
.TP 
\fB/server shakeup\fR
Randomly reform the teams.  [op]
.TP 
\fB/server reset\fR
Reset the scores.  [op]
.TP 
\fB/server map <\fImapname\fP>\fR
Load the map named <\fImapname\fP> and immediately start a new game.  [op]
.TP 
\fB/server newgame\fR
Declare a draw and start a new game, with the same map.  [op]
.TP 
\fB/server kick <\fIplayer\fP>\fR
Kick the player named <\fIplayer\fP> from the game.  [op]
.TP 
\fB/server shutdown\fR
Immediately shutdown the server.  [op]
.TP 
\fB/server help\fR
Display a summary of commands supported by the server.
.SH "CONFIGURATION"
.LP 
Various aspects of the server can be configured by a standard text file which has one configuration directive per line.  Blank lines and lines starting with a \fB#\fR or \fB;\fR are ignored.  Each configuration directive has the following syntax:
.LP
\fBoption_name option_value\fR
.LP 
At least one space or tab character must separate the \fBoption_name\fR from the \fBoption_value\fR.
.LP
The path to the server configuration file is specified by passing the \fB-c\fR command line option.  If no \fB-c\fR option is present, then no configuration file is loaded, and the defaults are used.  Note that some configuration options can also be specified using command line options.  Values specified on the command line \fIalways\fP override values specified in the configuration file.
.LP
The following options are supported.  Configuration directives containing an unrecognized option name are ignored.  Unless otherwise specified, all option values that specify times are in milliseconds.
.TP 
\fBpassword <\fIpassword\fP>\fR
Enable operator mode and set the operator password to <\fIpassword\fP>.  (command line option: \fB\-P\fR)
.TP 
\fBmap <\fImapname\fP>\fR
Set the server map to <\fImapname\fP>.  (command line option: \fB\-m\fR) (default: alpha1)
.TP 
\fBinterface <\fIinterface\fP>\fR
Listen only on the interface with address <\fIinterface\fP>.  (command line option: \fB\-i\fR) (by default, listen on all interfaces)
.TP 
\fBportno <\fIportno\fP>\fR
Listen on port <\fIportno\fP>.  (command line option: \fB\-p\fR) (default: 16877)
.TP 
\fBserver_name <\fIname\fP>\fR
Set the human\-readable server name to <\fIname\fP>.  If set, appears in the server browser in lieu of the hostname.
.TP 
\fBserver_location <\fIlocation\fP>\fR
Set the human\-readable geographic location of the server to <\fIlocation\fP>.  Not presently used, but in the future will appear in the server browser.
.TP 
\fBautobalance [\fI yes \fP|\fI no \fP]\fR
Specifies whether to enforce balanced teams.  When enabled, players are not permitted to switch teams if it would cause an imbalance, and when imbalances are caused by player departures, random players are switched until the teams are balanced.  (default: disabled)
.TP 
\fBregister_server [\fI yes \fP|\fI no \fP]\fR
Specifies whether to register the server with the global meta server.  When enabled, the server will appear in the server browsers of Internet players.  When disabled, the server will only appear in the server browsers of LAN users.  (default: enabled)
.SH "NOTES"
.LP 
If no operator password is set on the command line, then any player connecting from the localhost (127.0.0.1) will be given operator status.  If this is undesirable behavior, then be sure to set an operator password.  (However, see \fBBUGS\fR below.)
.LP 
By default, the Leges Motus server will contact the meta server so other players on the Internet can connect to and play on the server.  If you would NOT like your server to appear in server browsers of other Internet users, pass the \-l ("local") option to lmserver, or set the server configuration option "\fBregister_server\fR" to "no" (See  \fBCONFIGURATION\fR above).
.LP 
If a server is run behind a firewall, and it is registered with the meta server, the meta server will attempt to pierce the firewall so that clients outside the firewall are able to connect to the server.  However, this technique does not work with all firewalls, and is not 100% reliable.  If you intend to host a long\-running server behind a firewall, you are strongly recommended to modify your firewall settings to allow/forward UDP port 16877.
.SH "FILES"
.LP 
\fI$LM_DATA_DIR/maps\fP
.br 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBLM_DATA_DIR\fP
Specifies the location of the directory containing Leges Motus data files.
.TP 
\fBLM_METASERVER\fP
Specifies the address to use for registering with the meta server.  This is useful only for testing alternative meta servers, and should not be used generally. 
.SH "EXAMPLES"
.LP 
To run the server in the background:
.LP 
lmserver \-d
.LP 
To run Leges Motus every time you start your computer, you could put this in a system startup script (e.g. /etc/rc.local):
.LP 
lmserver \-d \-u nobody
.LP 
If you don't want to register your server with the meta server:
.LP 
legesmotus \-l
.LP 
Run the server with the gamma3 map:
.LP 
legesmotus \-m gamma3
.LP 
To set an operator password:
.LP 
legesmotus \-P foobar
.LP 
To authenticate with your operator password:
.LP 
/server auth foobar
.LP 
To kick an unruly player:
.LP 
/server kick Steve
.SH "AUTHORS"
.LP 
Andrew Ayer <agwadude@users.sourceforge.net>
.br 
Nathan Partlan <greywhind@users.sourceforge.net>
.br 
Jeffrey Pfau <archaemic@users.sourceforge.net>
.br 
.SH "COPYRIGHT"
.LP 
Copyright 2009 Andrew Ayer, Nathan Partlan, Jeffrey Pfau
.LP 
Leges Motus is free and open source software.  You may redistribute it and/or
modify it under the terms of version 2, or (at your option) version 3, of the
GNU General Public License (GPL), as published by the Free Software Foundation.
.LP 
Leges Motus is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the full text of the GNU General Public License for
further detail.
.LP 
For a full copy of the GNU General Public License, please see the COPYING file
in the root of the source code tree.  You may also retrieve a copy from
<\fBhttp://www.gnu.org/licenses/gpl\-2.0.txt\fR>, or request a copy by writing to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111\-1307  USA
.SH "BUGS"
.LP 
The operator password is set on the command line, meaning it's visible to any user on the system through a call to \fIps\fR\|(1).
.LP 
The protocol documentation is very out\-of\-date.
.SH "SEE ALSO"
.LP 
legesmotus(6)
